### PR TITLE
Remove broken facade

### PR DESCRIPTION
**Pull request by juliangums**
This broken facade is giving me some issues with static analysers. I tried to fix it first but as RadioDeck needs a name parameter when constructing, it doesn't really work well as a facade anyway. So it's better to clean this up.

### CODE REVIEW

**Comment by 199ocero** [comment]
Thank youuu @juliangums !

**Comment by jackwh** [comment]
@juliangums The changes made in dd568c7792b0350ed82b3ee6a047389c54e15c8d and deb10a94cca45f8d870c01439c18a9fd8a3451e1 are causing a fatal error when an Enum class is passed and used with the `HasDescriptions` and `HasIcons` interfaces, as per docs. Can this be reverted?

**Comment by juliangums** [comment]
I see the issue. Will fix shortly.

**Comment by juliangums** [comment]
Sorry about that @JackWH . I opened https://github.com/199ocero/radio-deck/pull/17
Can you confirm that works and we can merge it.

**Comment by JackWH** [comment]
Works great, thanks @juliangums!

**Pull request merged**
