### PR TITLE
Correct type hint

### PR DESCRIPTION
**Pull request by juliangums**

### CODE REVIEW

**Comment by jackwh** [comment]
Hey @juliangums, just tested and I can see each line causes a syntax error:

```php
protected Arrayable|Closure|string $descriptions = [];
```

> Cannot use array as default value for property JaOcero\RadioDeck\Forms\Components\RadioDeck::$descriptions of type Illuminate\Contracts\Support\Arrayable|Closure|string

You should extend the union type back to how it was originally, by adding `|array`:

```php
protected Arrayable|Closure|string|array $descriptions = [];
```

**Comment by juliangums** [comment]
@JackWH can you check again?

**Comment by 199ocero** [comment]
Merge @juliangums @JackWH yeah sorry I didn't check the last PR I thought it only removes the facade but some data type are remove. Can you check it again @JackWH ?

**Comment by juliangums** [comment]
My bad for not double-checking. I was experimenting with other parts of the code, and this should not have made it in the code. Was committed by accident.

**Pull request merged**
